### PR TITLE
Do parameter validation in clGetExtensionFunctionAddress

### PR DESCRIPTION
**Pull request by jeroenk**
Also undefine the local macros as soon as possible

### CODE REVIEW

**Comment by bashbaug** [comment]
+1, looks good to me.

This behavior matches the OpenCL Extensions Spec:

> A return value of NULL indicates that the specified function does not exist for the implementation or *platform* is not a valid platform.

**Comment by jeroenk** [comment]
This work was done on behalf of my employer at the time (Codeplay Software). Please contact them,

**Comment by alycm** [comment]
As a current Codeplay Software employee: I can cherry-pick this into a new PR and as I have already signed the CLA that should resolve the issue.

**Comment by kepatil** [comment]
@alycm Did you get a chance to create the new pull request? Till you do that I am keeping this PR open for tracking.

**Comment by alycm** [comment]
So for the delay Kedar, I have now done this in this pull request: https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/59

I will close this pull request now.

**Pull request closed without merging**
