### PR TITLE
Add support for OpenCL 3.0 Provisional

### PR DESCRIPTION
**Pull request by alycm**
The new entry points will only be enabled if `CL_EXPERIMENTAL` is manually set.

Note that even a non experimental libOpenCL.so ends up with an `OPENCL_EXPERIMENTAL` absolute symbol on Linux builds.  I don't think that that is a problem though, as it is not referenced.

### CODE REVIEW

**Comment by alycm** [comment]
I obviously skipped a lot of untested entry points in the PR, I've filed an issue about actually implementing those tests: https://github.com/KhronosGroup/OpenCL-ICD-Loader/issues/109.

**Comment by alycm** [comment]
I have updated this to OpenCL 3.0 provisional.  This is still off by default, the OPENCL_3.0 is present in Linux builds regardless, but this seems harmless.

Windows builds with 3.0 enabled may require adding two symbols to the export map, this could be resolved by having CMake generate that file, but I have no done that currently.

**Comment by alycm** [comment]
My thought was to use cmake `configure_file` or an equivalent mechanism, I'll take a look soon.

**Comment by alycm** [comment]
I've updated this PR to use `configure_file` to generate an `OpenCL.def` or `icd_exports.map` that will only include 3.0 symbols when `ENABLE_OPENCL30_PROVISIONAL` is set.  No manual intervention required.

Testing Linux both ways locally, Windows in progress.

**Comment by alycm** [comment]
Also now tested locally on Windows.

**Comment by bashbaug** [comment]
Thanks!  I've verified that this works with no manual intervention also.  Merging!

**Pull request merged**
