### PR TITLE
Add >VS2008 envvar

### PR DESCRIPTION
**Pull request by mirh**
[Idk](http://help.appveyor.com/discussions/kb/48-vs2017) about VS2017 then (which in other news also add native cmake support)

### CODE REVIEW

**Comment by bashbaug** [comment]
I think this is fine, but would it be even better to build using cmake instead of invoking `nmake` directly?

Then, the batch file could simply become:

````
set BUILD_DIR=build
set BIN_DIR=bin

mkdir %BUILD_DIR%
cd %BUILD_DIR%
cmake ../
cmake --build .
cd ..
````

**Comment by mirh** [comment]
Mh, well, that works too. 
I wouldn't be sure about pros and cons of the thing though. 
For example, a funny difference I noticed (aside from cmd spawning VS compiler logs, instead of a "gcc-like" progress screen) is that the exe manifest uses `'` instead of `"` now. 
This should be insignificant, but makes me wonder what's else.

**Comment by bashbaug** [comment]
Are the differences purely cosmetic?  I can't think of any good reason why one method would be any more right than the other, just different.

To be clear, I'm OK with the proposed changes as-is, though it would be nice to avoid needing an update for each new VS version.

@kepatil any thoughts?

**Comment by kepatil** [comment]
> Are the differences purely cosmetic? I can't think of any good reason why one method would be any more right than the other, just different.
> 
> To be clear, I'm OK with the proposed changes as-is, though it would be nice to avoid needing an update for each new VS version.
> 
> @kepatil any thoughts?

I think building using cmake as you suggested is better. I'll make that change.

**Comment by bashbaug** [comment]
We've removed the batch files and switched entirely to a CMake build system in #61, so I am closing this pull request.

**Pull request closed without merging**
