### PR TITLE
Some bugs encountered while building with VS 2017 64bit

### PR DESCRIPTION
**Pull request by SilverCamel**
Modified the code to reflect the changes to get rid of the bugs.

### CODE REVIEW

**Comment by kepatil** [comment]
@SilverCamel Thanks for creating the pull request! Just one more step needed: Khronos repositories require all contributors to sign the contributor license agreement (CLA) before accepting their changes. Please go to https://cla-assistant.io/KhronosGroup/OpenCL-ICD-Loader?pullRequest=39 to read the terms and accept them.

**Comment by kepatil** [comment]
Ping @SilverCamel to sign the CLA!

**Comment by SilverCamel** [comment]
Hello Kepatil,

Sorry for the delay in signing. Actually, I had done the CLA signing process a lot before but somehow
it did not registered or some problem must have occurred. 
I hope now it is okay.

thanks

**Comment by kepatil** [comment]
Thanks. Merged.

**Pull request merged**
