### PR TITLE
Statically link with VC++ Runtime

### PR DESCRIPTION
**Pull request by ArturHarasimiuk**
VC++ Runtime dynamic library may not be available in some cases. Thus,
by doing static linking it makes dll independent of already installed
software and can be used without problems.

Change-Id: I8bb71db2f3dc48bc9ec976cdbb597d2ec812ce54
Signed-off-by: Artur Harasimiuk <artur.harasimiuk@intel.com>

### CODE REVIEW

**Comment by bashbaug** [comment]
I think this is generally a fine idea and I've done similar in other project.  My only two questions are:

* The current change statically links for both the Debug and Release configs.  Is this needed?  I suspect static linking is most valuable in the Debug config, since otherwise the target needs the debug runtime installed?

* If we do decide to statically link for both the Debug and Release configs, should we also statically link other configs, such as MinSizeRel and RelWithDebInfo?

**Comment by ArturHarasimiuk** [comment]
It was my goal to do static link for Release version also because you may have OS setup where VC++ Runtime libraries are not installed. 

I added support for MinSizeRel and RelWithDebInfo. Thanks for pointing this out.

**Comment by bashbaug** [comment]
@kepatil, can you please review and merge this change?

I do see that statically linking increases the size of the ICD loader DLL slightly, but it's an increase from ~30KB to ~100KB, so it's relatively insignificant.

**Comment by isuruf** [comment]
Can you please provide a cmake option to not do this? Not everyone wants to statically link with VC++ runtime.

**Comment by isuruf** [comment]
Thanks @ArturHarasimiuk

**Pull request merged**
